branch-defaults:
  Isomorphic:
    environment: BookShopV3
    group_suffix: null
  Isomorphic-RouterV4:
    environment: BookShopApp
environment-defaults:
  BookShopApp:
    branch: null
    repository: null
  bookShop-universal-dev:
    branch: null
    repository: null
  bookShopRouterV4:
    branch: null
    repository: null
global:
  application_name: bookShop_universal
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
